name: "Carpool Vote - Vote America"
description: "Get a ride or share a ride in the 2016 US presidential election. Every American DESERVES a vote!"

markdown: kramdown
highlighter: pygments

permalink: :title/
relative_permalinks: false
baseurl: "/"